name: customAction2

on: push

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v4
   - name: test
     uses:  fadysaad66/HiveBox@main
     with:
      path: external-code
 
